import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";

import { CompactScreenHeader } from "@/components/compact-screen-header";
import { AdminSessionExpired } from "@/components/admin-session-expired";
import { GlowGlassCard } from "@/components/glow-glass-card";
import { MasterExportTools } from "@/components/master-export-tools";
import { MasterOverrideControls } from "@/components/master-override-controls";
import { MasterUserSearch } from "@/components/master-user-search";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useAuthSession } from "@/lib/auth-session";
import { trpc } from "@/lib/trpc";

const ROLES = ["super-admin", "owner", "admin", "staff", "caretaker", "guest"] as const;
const TABS = ["ledger", "members", "system"] as const;
type SimulationRole = (typeof ROLES)[number];
type Tab = (typeof TABS)[number];

export default function MasterControlScreen() {
  const colors = useColors();
  const { currentUser } = useAuthSession();
  const params = useLocalSearchParams<{ workspace?: string }>();
  const preselect = params.workspace && /^\d+$/.test(params.workspace) ? Number(params.workspace) : null;
  const [selectedId, setSelectedId] = useState<number | null>(preselect);
  const [activeTab, setActiveTab] = useState<Tab>("ledger");
  const [simulation, setSimulation] = useState<SimulationRole>("super-admin");
  const [message, setMessage] = useState<string | null>(null);
  const overview = trpc.masterControl.overview.useQuery(undefined, { retry: false });
  const workspace = trpc.masterControl.workspace.useQuery({ workspaceId: selectedId ?? 0 }, { enabled: Boolean(selectedId), retry: false });
  const simulate = trpc.masterControl.simulateRole.useMutation();
  const createRecovery = trpc.masterControl.createRecoveryPoint.useMutation();
  const restoreRecovery = trpc.masterControl.restoreRecoveryPoint.useMutation();
  const exportWorkspace = trpc.masterControl.exportWorkspace.useMutation();
  const serverSync = trpc.masterControl.forceServerSync.useMutation();
  const assignMembership = trpc.masterControl.assignMembership.useMutation();
  const isBusy = simulate.isPending || createRecovery.isPending || restoreRecovery.isPending || exportWorkspace.isPending || serverSync.isPending || assignMembership.isPending;
  const selectedWorkspace = useMemo(() => overview.data?.workspaces.find((entry) => entry.workspace.id === selectedId)?.workspace ?? null, [overview.data?.workspaces, selectedId]);
  const refresh = async () => { await Promise.all([overview.refetch(), selectedId ? workspace.refetch() : Promise.resolve()]); };
  const confirm = (title: string, text: string, action: () => Promise<void>) => Alert.alert(title, text, [{ text: "إلغاء", style: "cancel" }, { text: "متابعة", onPress: () => void action().catch(() => setMessage("تعذر إتمام الإجراء. تحقق من اتصالك وصلاحية الإدارة العليا.")) }]);
  const runSimulation = async () => { if (!selectedId) return; const result = await simulate.mutateAsync({ workspaceId: selectedId, role: simulation }); setMessage(`تم تسجيل محاكاة دور «${roleLabel(result.role)}». هذه المحاكاة لا تغيّر الجلسة أو صلاحيات المستخدمين.`); await refresh(); };
  const exportSelected = async () => { if (!selectedId) return; const data = await exportWorkspace.mutateAsync({ workspaceId: selectedId, confirmation: "EXPORT-WORKSPACE" }); await Share.share({ title: `StayIn — ${data.workspace.name}`, message: JSON.stringify(data, null, 2) }); setMessage("تم تجهيز نسخة JSON للمشاركة دون تعديل بيانات المنشأة."); await refresh(); };
  const toggleMember = async (member: NonNullable<typeof workspace.data>["members"][number]) => { if (!selectedId || member.role === "owner") return; if (member.userId === currentUser?.id) { setMessage("هذه العضوية هي حساب السوبر أدمن الأساسي (#U1000) — محصّنة بالحصانة النظامية ولا يمكن تعليقها."); return; } const status = member.status === "active" ? "disabled" : "active"; await assignMembership.mutateAsync({ confirmation: "ADMIN-OVERRIDE", workspaceId: selectedId, userId: member.userId, displayName: member.displayName, phone: member.phone, role: member.role, permissions: member.permissions, status }); setMessage(status === "active" ? `تم تفعيل عضوية ${member.displayName}.` : `تم تعليق عضوية ${member.displayName}.`); await refresh(); };

  if (overview.isLoading) return <ScreenContainer><View style={styles.center}><ActivityIndicator color={colors.primary} /><Text style={{ color: colors.muted }}>جارٍ التحقق من صلاحية الإدارة العليا…</Text></View></ScreenContainer>;
  if (overview.error?.data?.code === "UNAUTHORIZED") return <AdminSessionExpired />;
  if (overview.error && overview.error.data?.code !== "FORBIDDEN") return <ScreenContainer><View style={styles.center}><MaterialIcons name="wifi-off" size={38} color={colors.error} /><Text style={[styles.deniedTitle, { color: colors.foreground }]}>تعذر الاتصال بخادم الإدارة العليا</Text><Text style={[styles.deniedText, { color: colors.muted }]}>لم تصل البيانات من الخادم الآن. تحقق من اتصالك أو أعد محاولة الاتصال قبل فتح أدوات التحكم.</Text><Pressable onPress={() => overview.refetch()} style={[styles.backButton, { backgroundColor: colors.primary }]}><Text style={styles.whiteText}>إعادة المحاولة</Text></Pressable><Pressable onPress={() => router.replace("/(tabs)/more")} style={[styles.backButton, { backgroundColor: "transparent", borderWidth: 1, borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: "800" }}>العودة إلى المزيد</Text></Pressable></View></ScreenContainer>;
  if (overview.error) return <ScreenContainer><View style={styles.center}><MaterialIcons name="lock-outline" size={38} color={colors.error} /><Text style={[styles.deniedTitle, { color: colors.foreground }]}>هذه اللوحة مخصصة لمدير النظام فقط</Text><Text style={[styles.deniedText, { color: colors.muted }]}>تُفرض صلاحية الإدارة العليا من الخادم، ولا يكفي الوصول إلى هذا الرابط لفتح أدوات التحكم.</Text><Pressable onPress={() => router.replace("/(tabs)/more")} style={[styles.backButton, { backgroundColor: colors.primary }]}><Text style={styles.whiteText}>العودة إلى المزيد</Text></Pressable></View></ScreenContainer>;

  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
    <CompactScreenHeader title="مركز الإدارة العليا" icon="admin-panel-settings" accentColor={colors.primary} backHref="/(tabs)/more" showDateTime={false} />
    {currentUser ? <View style={[styles.identityCard, { backgroundColor: colors.surface, borderColor: colors.primary + "44" }]}><View style={[styles.identityAvatar, { backgroundColor: colors.primary + "16" }]}><MaterialIcons name="admin-panel-settings" size={22} color={colors.primary} /></View><View style={styles.flex}><View style={styles.identityRoleRow}><Text style={[styles.identityRole, { color: colors.primary }]}>مدير النظام · Super Admin</Text><View style={[styles.identityBadge, { backgroundColor: colors.primary + "18" }]}><Text style={[styles.identityBadgeText, { color: colors.primary }]}>{currentUser.userCode ?? `#${currentUser.id}`}</Text></View></View><Text numberOfLines={1} style={[styles.identityName, { color: colors.foreground }]}>{currentUser.fullName}</Text><Text numberOfLines={1} style={[styles.identityMeta, { color: colors.muted }]}>{[currentUser.email, currentUser.phone].filter(Boolean).join(" · ") || "بيانات الحساب غير مكتملة"}</Text><Text style={[styles.identityShield, { color: colors.success }]}>محصّن بالحصانة النظامية · لا يمكن حذفه أو تعليقه أو تعديل رتبته</Text></View><Pressable accessibilityRole="button" accessibilityLabel="فتح الملف الشخصي" onPress={() => router.push("/profile")} style={({ pressed }) => [styles.identityProfileLink, { opacity: pressed ? 0.72 : 1 }]}><MaterialIcons name="person-outline" size={19} color={colors.primary} /><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "900" }}>الملف</Text></Pressable></View> : null}
    <View style={[styles.notice, { backgroundColor: colors.primary + "10", borderColor: colors.primary + "55" }]}><MaterialIcons name="verified-user" size={21} color={colors.primary} /><Text style={[styles.noticeText, { color: colors.foreground }]}>كل عملية حساسة تحتاج تأكيدًا وتُسجّل خادميًا. محاكاة الأدوار للعرض والاختبار فقط ولا تمنح صلاحيات فعلية.</Text></View>
    <Pressable onPress={() => router.push("/admin/qa-sandbox")} style={({ pressed }) => [styles.qaSandboxLink, { backgroundColor: colors.primary + "10", borderColor: colors.primary + "55", opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="science" size={20} color={colors.primary} /><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>مختبر الأدوار والمنشآت</Text><Text style={[styles.rowText, { color: colors.muted }]}>توليد بيانات اختبار معزولة ومحاكاة الموظف متعدد المنشآت.</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.primary} /></Pressable>
    <Pressable onPress={() => router.push("/admin/master-blackout" as never)} style={({ pressed }) => [styles.qaSandboxLink, { backgroundColor: colors.error + "12", borderColor: colors.error + "66", opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="gpp-bad" size={20} color={colors.error} /><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>🔒 إدارة الحجب المركزي والتعليق الشامل للوحدات</Text><Text style={[styles.rowText, { color: colors.muted }]}>مفاتيح الحجب العليا للشاشات الـ13 وشبكة التعليق الشامل المؤقت — حصري لمدير النظام #U1000.</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.error} /></Pressable>
    <Pressable onPress={() => router.push("/admin/system-health-errors" as never)} style={({ pressed }) => [styles.qaSandboxLink, { backgroundColor: colors.success + "12", borderColor: colors.success + "55", opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="monitor-heart" size={20} color={colors.success} /><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>مركز رصد الأخطاء وصحة النظام</Text><Text style={[styles.rowText, { color: colors.muted }]}>مراقبة فورية لنبض السيرفر، قواعد البيانات، وسجل الأخطاء الحية وتتبع المشاكل.</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.success} /></Pressable>
    <Pressable onPress={() => router.push("/admin/user-diagnostics" as never)} style={({ pressed }) => [styles.qaSandboxLink, { backgroundColor: colors.primary + "10", borderColor: colors.primary + "55", opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="manage-accounts" size={20} color={colors.primary} /><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>تشخيص وفحص الحسابات (User Doctor)</Text><Text style={[styles.rowText, { color: colors.muted }]}>فحص تسلسلي آلي لحالات المستخدمين، التوثيق، الصلاحيات، والجلسات النشطة.</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.primary} /></Pressable>
    <Pressable onPress={() => router.push("/admin/deletion-management" as never)} style={({ pressed }) => [styles.qaSandboxLink, { backgroundColor: colors.error + "14", borderColor: colors.error + "66", opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="delete-forever" size={20} color={colors.error} /><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>إدارة الحذف النهائي والمهلة الزمنية</Text><Text style={[styles.rowText, { color: colors.muted }]}>إزالة دائمة لحسابات الاختبار مع مهلة ١٤ يومًا، معاينة شاملة لكل السجلات، وأرشيف للمحذوفات يوثّق المنفّذ.</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.error} /></Pressable>
    <Pressable onPress={() => router.push("/admin/workspaces-directory" as never)} style={({ pressed }) => [styles.qaSandboxLink, { backgroundColor: colors.primary + "10", borderColor: colors.primary + "55", opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="domain" size={20} color={colors.primary} /><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>دليل المنشآت وإدارة المستأجرين</Text><Text style={[styles.rowText, { color: colors.muted }]}>مؤشرات إجمالية للمنشآت والأعضاء، وبحث فوري، ثم فتح أدوات التشغيل أو إدارة منشأة محددة.</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.primary} /></Pressable>
    {selectedWorkspace ? <><View style={[styles.tabs, { backgroundColor: colors.surface, borderColor: colors.border }]}>{TABS.map((tab) => <Pressable key={tab} onPress={() => setActiveTab(tab)} style={[styles.tab, { backgroundColor: activeTab === tab ? colors.primary : "transparent" }]}><MaterialIcons name={tab === "ledger" ? "account-balance-wallet" : tab === "members" ? "groups" : "cloud-sync"} size={16} color={activeTab === tab ? colors.background : colors.muted} /><Text style={{ color: activeTab === tab ? colors.background : colors.foreground, fontSize: 10, fontWeight: "900" }}>{tabLabel(tab)}</Text></Pressable>)}</View>
      {activeTab === "ledger" ? <View style={styles.tabContent}><MasterOverrideControls workspaceId={selectedId!} disabled={isBusy} onCompleted={async (nextMessage) => { setMessage(nextMessage); await refresh(); }} /></View> : null}
      {activeTab === "members" ? <View style={styles.tabContent}><Section title={`محاكاة الأدوار — ${selectedWorkspace.name}`} colors={colors}><Text style={[styles.hint, { color: colors.muted }]}>اختبر ما يمكن رؤيته وصلاحيات الدور الافتراضية دون تبديل الجلسة أو تعديل عضويات المنشأة.</Text><View style={styles.roleGrid}>{ROLES.map((role) => <Pressable key={role} onPress={() => setSimulation(role)} style={[styles.roleChip, { backgroundColor: simulation === role ? colors.primary : colors.surface, borderColor: simulation === role ? colors.primary : colors.border }]}><Text style={{ color: simulation === role ? colors.background : colors.foreground, fontWeight: "900", fontSize: 11 }}>{roleLabel(role)}</Text></Pressable>)}</View><ActionButton label="تسجيل المحاكاة" icon="account-tree" color={colors.primary} disabled={isBusy} onPress={() => void runSimulation()} /></Section><Section title="إدارة عضويات المنشأة" colors={colors}><Text style={[styles.hint, { color: colors.muted }]}>يمكن تفعيل أو تعليق عضوية الموظف في المنشأة المحددة. لا يمكن تغيير عضوية المالك من هذه اللوحة.</Text>{workspace.data?.members.map((member) => <Pressable key={member.id} disabled={member.role === "owner" || member.userId === currentUser?.id || isBusy} onPress={() => confirm(member.status === "active" ? "تعليق عضوية" : "تفعيل عضوية", `هل تريد ${member.status === "active" ? "تعليق" : "تفعيل"} ${member.displayName} في هذه المنشأة؟`, () => toggleMember(member))} style={[styles.memberRow, { backgroundColor: colors.surface, borderColor: member.status === "active" ? colors.border : colors.primary + "88", opacity: member.role === "owner" || member.userId === currentUser?.id ? 0.55 : 1 }]}><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{member.displayName}</Text><Text style={[styles.rowText, { color: colors.muted }]}>{roleLabel(member.role)} · {member.status === "active" ? "نشط" : "معلق"}</Text></View><MaterialIcons name={member.userId === currentUser?.id ? "gpp-good" : member.role === "owner" ? "stars" : member.status === "active" ? "lock-open" : "lock-outline"} size={21} color={member.role === "owner" ? colors.primary : member.status === "active" ? colors.success : colors.primary} /></Pressable>)}</Section><MasterUserSearch workspaceId={selectedId!} disabled={isBusy} onAssigned={async (nextMessage) => { setMessage(nextMessage); await refresh(); }} /></View> : null}
      {activeTab === "system" ? <View style={styles.tabContent}><Section title="مركز التحكم في الميزات" colors={colors}><Text style={[styles.hint, { color: colors.muted }]}>مفاتيح الحجب المركزي للميزات والوحدات التشغيلية ولوحة تفعيل الشاشات والأدوات للملاك.</Text><ActionButton label="فتح مركز التحكم في الميزات" icon="tune" color={colors.primary} disabled={false} onPress={() => router.push("/feature-control" as never)} /></Section><Section title="المزامنة والاسترداد" colors={colors}><ActionButton label="إنشاء نقطة استرداد" icon="add-circle-outline" color={colors.primary} disabled={isBusy || !workspace.data?.snapshot} onPress={() => confirm("إنشاء نقطة استرداد", "سيُحفظ إصدار قابل للاستعادة قبل أي تدخل لاحق.", async () => { await createRecovery.mutateAsync({ workspaceId: selectedId!, confirmation: "ADMIN-OVERRIDE", reason: "manual-super-admin-recovery" }); setMessage("تم إنشاء نقطة الاسترداد."); await refresh(); })} /><ActionButton label="تحميل حالة الخادم الحالية" icon="sync" color={colors.primary} disabled={isBusy || !workspace.data?.snapshot} onPress={() => confirm("تحميل حالة الخادم", "سيتم طلب أحدث لقطة خادمية للمراجعة، دون استبدال بيانات الجهاز تلقائيًا.", async () => { const result = await serverSync.mutateAsync({ workspaceId: selectedId!, confirmation: "SYNC-WORKSPACE" }); setMessage(`الخادم يعرض الإصدار ${result.version} المحدث في ${new Date(result.updatedAt).toLocaleString("ar-JO")}.`); await refresh(); })} /><ActionButton label="تصدير نسخة JSON" icon="download" color={colors.success} disabled={isBusy} onPress={() => confirm("تصدير بيانات المنشأة", "ستُجهز نسخة JSON للمشاركة. تأكد من مشاركتها عبر قناة موثوقة فقط.", exportSelected)} />{workspace.data?.recoveryPoints.map((point) => <Pressable key={point.id} onPress={() => confirm("استعادة نسخة منشأة", "ستُنشأ نسخة احتياطية من الحالة الحالية أولًا، ثم تُستعاد هذه النقطة لجميع بيانات المنشأة.", async () => { await restoreRecovery.mutateAsync({ workspaceId: selectedId!, backupId: point.id, confirmation: "ADMIN-OVERRIDE" }); setMessage("اكتملت الاستعادة وأنشئت نسخة للحالة السابقة."); await refresh(); })} style={[styles.recoveryRow, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={styles.flex}><Text style={[styles.rowTitle, { color: colors.foreground }]}>نقطة استرداد #{point.id}</Text><Text style={[styles.rowText, { color: colors.muted }]}>إصدار {point.sourceVersion} · {new Date(point.createdAt).toLocaleString("ar-JO")}</Text></View><MaterialIcons name="restore" size={21} color={colors.primary} /></Pressable>)}</Section><MasterExportTools workspaceId={selectedId!} disabled={isBusy} onCompleted={async (nextMessage) => { setMessage(nextMessage); await refresh(); }} /><AuditTrail audit={overview.data?.audit ?? []} colors={colors} /></View> : null}
    </> : <View style={[styles.emptySelection, { borderColor: colors.border, backgroundColor: colors.surface }]}><MaterialIcons name="touch-app" size={26} color={colors.primary} /><Text style={[styles.emptySelectionText, { color: colors.muted }]}>اختر منشأة من «دليل المنشآت وإدارة المستأجرين» لفتح تبويبات التحكم التشغيلية الخاصة بها.</Text></View>}
    {message ? <View style={[styles.message, { backgroundColor: colors.primary + "10", borderColor: colors.primary + "55" }]}><MaterialIcons name="info-outline" size={18} color={colors.primary} /><Text style={[styles.messageText, { color: colors.foreground }]}>{message}</Text></View> : null}
  </ScrollView></ScreenContainer>;
}

function AuditTrail({ audit, colors }: { audit: Array<{ id: number; action: string; actorName: string; createdAt: Date; targetWorkspaceId: number | null; targetMemberId: number | null }>; colors: ReturnType<typeof useColors> }) { return <Section title="سجل الإدارة العليا" colors={colors}>{audit.slice(0, 5).length ? audit.slice(0, 5).map((item) => <View key={item.id} style={[styles.auditRow, { borderColor: colors.primary + "55", backgroundColor: colors.surface }]}><MaterialIcons name="history" size={18} color={colors.primary} /><View style={styles.flex}><Text style={[styles.auditTitle, { color: colors.foreground }]}>{auditLabel(item.action)}</Text><Text style={[styles.rowText, { color: colors.muted }]}>{item.actorName} · {auditTarget(item)} · {new Date(item.createdAt).toLocaleString("ar-JO")}</Text></View><View style={[styles.auditBadge, { backgroundColor: colors.primary + "18" }]}><Text style={[styles.auditBadgeText, { color: colors.primary }]}>موثق</Text></View></View>) : <Text style={[styles.hint, { color: colors.muted }]}>لا توجد عمليات إدارية مسجلة بعد.</Text>}</Section>; }
function Section({ title, colors, children }: { title: string; colors: ReturnType<typeof useColors>; children: React.ReactNode }) { return <View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{title}</Text><GlowGlassCard style={styles.sectionBody} contentStyle={styles.sectionBodyContent}>{children}</GlowGlassCard></View>; }
function ActionButton({ label, icon, color, disabled, onPress }: { label: string; icon: React.ComponentProps<typeof MaterialIcons>["name"]; color: string; disabled: boolean; onPress: () => void }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.actionButton, { borderColor: color + "88", backgroundColor: color + "10", opacity: pressed || disabled ? 0.5 : 1 }]}><MaterialIcons name={icon} size={20} color={color} /><Text style={[styles.actionText, { color }]}>{label}</Text><MaterialIcons name="chevron-left" size={20} color={color} /></Pressable>; }
function roleLabel(role: SimulationRole | "owner" | "admin" | "staff" | "caretaker" | "guest") { return role === "super-admin" ? "مدير النظام" : role === "owner" ? "مالك المنشأة" : role === "admin" ? "مدير المنشأة" : role === "staff" ? "موظف حجوزات" : role === "caretaker" ? "حارس / مشرف ميداني" : "ضيف"; }
function tabLabel(tab: Tab) { return tab === "ledger" ? "الحجوزات والمالية" : tab === "members" ? "العضويات والمحاكاة" : "النظام والمزامنة"; }
function auditLabel(action: string) { const labels: Record<string, string> = { "role-simulation": "محاكاة دور", "membership-updated": "تحديث عضوية", "recovery-point-created": "إنشاء نقطة استرداد", "recovery-point-restored": "استعادة نقطة بيانات", "workspace-exported": "تصدير نسخة منشأة", "server-sync-requested": "طلب مزامنة خادمية", "booking-overridden": "تدخل إداري في حجز", "expense-overridden": "تدخل إداري في مصروف", "expense-deleted": "حذف مصروف إداري", "identity-reset-requested": "طلب إعادة ضبط الهوية" }; return labels[action] ?? action; }
function auditTarget(item: { targetWorkspaceId: number | null; targetMemberId: number | null }) { return item.targetWorkspaceId ? `المنشأة #${item.targetWorkspaceId}` : item.targetMemberId ? `العضوية #${item.targetMemberId}` : "مستوى النظام"; }

const styles = StyleSheet.create({
  content: { padding: 16, paddingBottom: 120 }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, padding: 28 }, deniedTitle: { fontSize: 19, fontWeight: "900", textAlign: "center" }, deniedText: { fontSize: 13, lineHeight: 20, textAlign: "center" }, backButton: { minHeight: 46, paddingHorizontal: 18, borderRadius: 14, alignItems: "center", justifyContent: "center", marginTop: 8 }, whiteText: { color: "#FFFFFF", fontWeight: "900" },
  notice: { marginTop: 14, borderRadius: 16, borderWidth: 1, padding: 12, flexDirection: "row-reverse", gap: 9, alignItems: "center" }, noticeText: { flex: 1, fontSize: 11, fontWeight: "800", textAlign: "right", lineHeight: 17 }, qaSandboxLink: { marginTop: 10, minHeight: 62, borderRadius: 15, borderWidth: 1, paddingHorizontal: 12, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, section: { marginTop: 18 }, sectionTitle: { fontSize: 15, fontWeight: "900", textAlign: "right", marginBottom: 8 }, sectionBody: { borderRadius: 18 }, sectionBodyContent: { padding: 11, gap: 9 },
  flex: { flex: 1, minWidth: 0 }, rowTitle: { fontSize: 13, fontWeight: "900", textAlign: "right" }, rowText: { fontSize: 10, marginTop: 3, textAlign: "right" }, hint: { fontSize: 11, lineHeight: 17, textAlign: "right" },
  tabs: { marginTop: 18, minHeight: 49, borderWidth: 1, borderRadius: 15, padding: 4, flexDirection: "row-reverse", gap: 3 }, tab: { flex: 1, borderRadius: 11, justifyContent: "center", alignItems: "center", gap: 3, paddingHorizontal: 3 }, tabContent: { marginTop: 2 }, emptySelection: { marginTop: 20, minHeight: 115, borderWidth: 1, borderRadius: 18, alignItems: "center", justifyContent: "center", padding: 18, gap: 8 }, emptySelectionText: { textAlign: "center", fontSize: 12, lineHeight: 19 },
  roleGrid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, roleChip: { minHeight: 36, borderWidth: 1, borderRadius: 11, paddingHorizontal: 10, justifyContent: "center", alignItems: "center" }, actionButton: { minHeight: 48, borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, flexDirection: "row-reverse", alignItems: "center", gap: 9 }, actionText: { flex: 1, fontSize: 12, textAlign: "right", fontWeight: "900" }, recoveryRow: { minHeight: 54, borderWidth: 1, borderRadius: 13, paddingHorizontal: 10, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, memberRow: { minHeight: 56, borderWidth: 1, borderRadius: 13, paddingHorizontal: 10, flexDirection: "row-reverse", alignItems: "center", gap: 8 },
  auditRow: { minHeight: 58, borderWidth: 1, borderRadius: 13, paddingHorizontal: 10, paddingVertical: 8, flexDirection: "row-reverse", alignItems: "center", gap: 8, marginBottom: 7 }, auditTitle: { fontSize: 12, fontWeight: "900", textAlign: "right" }, auditBadge: { borderRadius: 8, paddingHorizontal: 7, paddingVertical: 4 }, auditBadgeText: { fontSize: 9, fontWeight: "900" }, message: { marginTop: 18, padding: 12, borderWidth: 1, borderRadius: 14, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, messageText: { flex: 1, fontSize: 11, lineHeight: 17, textAlign: "right", fontWeight: "800" },
  identityCard: { marginTop: 14, minHeight: 70, borderRadius: 18, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10, flexDirection: "row-reverse", alignItems: "center", gap: 9 }, identityAvatar: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center", flexShrink: 0 }, identityRoleRow: { flexDirection: "row", alignItems: "center", gap: 6 }, identityRole: { fontSize: 10, fontWeight: "900" }, identityBadge: { borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3 }, identityBadgeText: { fontSize: 9, fontWeight: "900" }, identityName: { fontSize: 15, fontWeight: "900", marginTop: 3 }, identityMeta: { fontSize: 10, marginTop: 3 }, identityShield: { fontSize: 9, marginTop: 4, fontWeight: "800" }, identityProfileLink: { minHeight: 34, borderRadius: 10, paddingHorizontal: 9, flexDirection: "row-reverse", alignItems: "center", gap: 4, flexShrink: 0 },
});
