import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const source = readFileSync(resolve(process.cwd(), "app/booking-detail.tsx"), "utf8");
const storeSource = readFileSync(resolve(process.cwd(), "lib/booking-store.tsx"), "utf8");

describe("Booking detail compact layout", () => {
  it("keeps payment and the paired edit-cancellation actions available without deletion", () => {
    expect(source).toContain("const [refundExpanded, setRefundExpanded]");
    expect(source).toContain("const [paymentSheetOpen, setPaymentSheetOpen]");
    expect(source).toContain("styles.paymentTrigger");
    expect(source).toContain("styles.bookingActionPair");
    expect(source).toContain("visible={paymentSheetOpen}");
    expect(source).toContain("visible={cancellationOpen}");
    expect(source).toContain("سبب الإلغاء (اختياري)");
    expect(source).toContain("cancelBooking(booking.id, cancellationReason)");
    expect(source).toContain("تم تحديث تفاصيل الحجز بنجاح");
    expect(source).toContain("booking.bookingReference");
    expect(source).toContain("weekdayLabel(booking.startDate, language)");
    expect(source).toContain("justifyContent: \"space-between\"");
    expect(source).toContain("const periodDescription");
    expect(source).toContain("durationLabel(booking, settings, language)");
    expect(source).toContain("styles.periodIdentityGrid");
    expect(source).toContain("backgroundColor: type.text + \"14\"");
    expect(source).toContain("borderColor: colors.error + \"88\"");
    expect(source).toContain("backgroundColor: bookingChalet?.color ?? colors.primary");
    expect(source).toContain('language === "ar" ? "شاليه" : "Chalet"');
    expect(source).toContain("visible={editConfirmationOpen}");
    expect(source).toContain("setTimeout(() => router.push");
    expect(source).toContain("bookingOccupancyStatus(booking)");
    expect(source).toContain("تم استرداد التأمين");
    expect(source).toContain("التأمين بانتظار الاسترداد");
    expect(source).toContain("const canRefundDeposit = depositRecorded > 0 && depositHeld > 0;");
    expect(source).toContain("depositRecorded <= 0");
    expect(source).toContain("تم استرداد التأمين بالكامل ولا يمكن إضافة دفعة أخرى.");
    expect(source).toContain("styles.periodIdentityGrid");
    expect(source).toContain("styles.periodChaletItem");
    expect(source).toContain("styles.periodTypeItem");
    expect(source).toContain("styles.periodReferenceItem");
    expect(source).toContain("flexBasis: 0");
    expect(source).toContain("const rentalFullyPaid = rentalBalance <= 0;");
    expect(source).toContain('language === "ar" ? "مدفوع بالكامل" : "Paid in full"');
    expect(source).toContain("!rentalFullyPaid ? <Pressable");
    expect(source).toContain("styles.financialCard");
    expect(source).toContain("الإيصالات المالية");
    expect(source).toContain("سجل الحركات الموحد");
    expect(source).toContain("const bookingTimeline: BookingTimelineEntry[]");
    expect(source).toContain('action: item.kind === "payment" ? "rental-payment" : "deposit-refund"');
    expect(source).toContain("const [timelineExpanded, setTimelineExpanded]");
    expect(source).toContain("accessibilityState={{ expanded: timelineExpanded }}");
    expect(source).toContain('timelineExpanded ? "keyboard-arrow-up" : "keyboard-arrow-down"');
    expect(source).toContain("depositState !== \"fully-refunded\"");
    expect(source).toContain("const waitlistConversion = waitlist.find");
    expect(source).toContain("entry.promotedBookingId === booking.id");
    expect(source).toContain("تم تحويل الطلب من قائمة الانتظار إلى حجز مؤكد.");
    expect(source).toContain("تم تسجيل الحجز");
    expect(source).toContain("const bookingCreatorName");
    expect(source).toContain("مركز التعديلات والإجراءات");
    expect(source).toContain("تعديل وقت الوصول / المغادرة");
    expect(source).toContain("تعديل الدفعات والمبالغ");
    expect(source).toContain("تعديل تفاصيل الحجز");
    expect(source).toContain("حجز جديد بنفس العميل");
    expect(source).toContain("إضافة دفعة إيجار");
    expect(source).toContain("const [refundPaymentMethod, setRefundPaymentMethod]");
    expect(source).toContain("طريقة استرداد التأمين");
    expect(source).toContain("movementPaymentMethodLabel(item.paymentMethod)");
    expect(source).toContain("shareBookingReceipt");
    expect(source).toContain("تفاصيل الإقامة");
    expect(source).toContain("جاري تجهيز الإيصال");
    expect(source).toContain("paymentMethodOptions");
    expect(source).toContain('id: "cash-owner"');
    expect(source).toContain('id: "cash-guardian"');
    expect(source).toContain('id: "click"');
    expect(source).not.toContain('id: "bank-transfer"');
    expect(source).not.toContain('id: "wallet"');
    expect(source).toContain("const openPaymentSheet = () => {");
    expect(source).toContain("setAmount(rentalBalance.toFixed(2));");
    expect(source).toContain("const [paymentMethod, setPaymentMethod] = useState<PaymentMethod | null>(null);");
    expect(source).toContain("اختر طريقة الدفع");
    expect(source).toContain("يرجى اختيار طريقة الدفع للمتابعة");
    expect(source).toContain("يرجى إدخال مبلغ صحيح للدفعة");
    expect(source).toContain("const [paymentConfirmation, setPaymentConfirmation]");
    expect(source).toContain('kind: "partial"');
    expect(source).toContain('kind: "over"');
    expect(source).toContain("visible={Boolean(paymentConfirmation)}");
    expect(source).toContain("تم إدخال دفعة جزئية، سيبقى على الحجز مبلغ");
    expect(source).toContain("المبلغ المدخل أكبر من الرصيد المتبقي، هل أنت متأكد من المتابعة؟");
    expect(source).toContain("const recordPayment = async");
    expect(storeSource).not.toContain("amount > rentalBalance(booking)");
    expect(source).toContain("paymentAmountRow");
    expect(source).toContain("paymentAmountNoteInput");
    expect(source).toContain("paymentAmountCaption");
    expect(source).toContain("ملاحظة اختيارية");
    expect(source).toContain("isRTL ? [...paymentMethodOptions].reverse() : paymentMethodOptions");
    expect(source).toContain("paymentMethod === method.id ? colors.success");
    expect(source).toContain("onPress={openPaymentSheet}");
    expect(source).toContain("paymentFormStyles.paymentAmountInput");
    expect(source).toContain("المبلغ الافتراضي هو الرصيد المتبقي ويمكن تعديله");
    expect(source).toContain('paymentMethodRow: { flexWrap: "nowrap" }');
    expect(source).toContain("إرفاق وصل");
    expect(source).toContain("استرداد سريع للتأمين");
    expect(source).toContain("إدارة الحجز والدفعات وأوقات الإقامة من مكان واحد");
    expect(source).toContain("const startPaymentEdit");
    expect(source).toContain("const confirmPaymentVoid");
    expect(source).toContain("تم إلغاء الدفعة");
    expect(source).toContain("المتبقي: ${formatMoney(rentalBalance, settings.currency)}");
    expect(source).not.toContain("إجراءات متقدمة");
    expect(source).not.toContain("deleteBooking");
  });

  it("places the chalet first and keeps rental and deposit titles on the Arabic reading edge", () => {
    expect(source).toContain('styles.periodIdentityGrid, { flexDirection: "row" }');
    expect(source).toContain("styles.periodReferenceItem");
    expect(source).toContain("styles.periodTypeItem");
    expect(source).toContain("styles.periodChaletItem");
    expect(source).toContain('styles.depositHeader, { flexDirection: "row"');
    expect(source).not.toContain("const detailRow");
  });
});
