import { useAppPreferences } from "./app-preferences";

export type TranslationKey =
  | "appName" | "welcome" | "home" | "bookings" | "calendar" | "reports" | "settings" | "waitlist" | "more" | "crm" | "notifications" | "maintenance"
  | "addBooking" | "noBookings" | "quickActions" | "totalBookings" | "paid" | "remaining" | "finalRevenue" | "discounts" | "bookingCount" | "today" | "upcoming"
  | "bookingDetails" | "customerData" | "customerName" | "phone" | "chaletName" | "period" | "startDate" | "endDate" | "startTime" | "endTime" | "bookingSummary" | "bookingType" | "discount" | "finalPrice" | "remainingAfterPayments" | "amountsAndPayments" | "basePrice" | "depositAmount" | "paymentAmount" | "notes" | "saveBooking" | "cancel" | "close" | "back"
  | "morning" | "evening" | "fullDay" | "customPeriod" | "multiDay" | "waiting" | "weekend"
  | "confirmed" | "awaitingDeposit" | "cancelled" | "completed" | "waitlisted" | "unpaid" | "deposit" | "partial" | "paidInFull"
  | "previous" | "next" | "noBookingsOrWaitlist" | "allChalets" | "unselectedChalet" | "continuous"
  | "appearance" | "day" | "dark" | "automatic" | "deviceSettings" | "useDeviceLanguage" | "useDeviceAppearance" | "haptics" | "notifications" | "respectFontScale" | "dateTimeSettings" | "timezone" | "deviceLanguage" | "deviceTimezone" | "language" | "english" | "arabic" | "saveSettings" | "periodSettings" | "businessName" | "businessPhone" | "defaultCurrency" | "weekendPrice" | "backup" | "exportBackup" | "importBackup" | "localBackupDescription" | "timeSettingsDescription" | "useDeviceLanguageDescription" | "useDeviceAppearanceDescription" | "hapticsDescription" | "notificationsDescription" | "fontScaleDescription" | "timezoneDescription" | "saved" | "savedSettings"
  | "filePreview" | "fileReady" | "fileDetails" | "detectedBookings" | "detectedWaitlist" | "replaceFile" | "confirmImport" | "importWarning" | "importComplete" | "importCompleteDescription" | "fileSize" | "unknownFileSize" | "noBookingsInFile";

type TranslationMap = Record<TranslationKey, string>;

const ar: TranslationMap = {
  appName: "منشأتي للحجوزات", welcome: "مرحبًا بك", home: "الرئيسية", bookings: "الحجوزات", calendar: "التقويم", reports: "التقارير", settings: "الإعدادات", waitlist: "الانتظار", more: "المزيد", crm: "الزبائن", notifications: "الإشعارات", maintenance: "الصيانة",
  addBooking: "إضافة حجز جديد", noBookings: "لا توجد حجوزات", quickActions: "إجراءات سريعة", totalBookings: "إجمالي الحجوزات", paid: "مدفوع", remaining: "متبقي", finalRevenue: "الإيرادات النهائية", discounts: "إجمالي الخصومات", bookingCount: "عدد الحجوزات", today: "اليوم", upcoming: "القادمة",
  bookingDetails: "تفاصيل الحجز", customerData: "بيانات العميل", customerName: "اسم العميل", phone: "رقم الهاتف", chaletName: "اسم الشاليه", period: "الفترة الميلادية", startDate: "تاريخ البداية", endDate: "تاريخ النهاية", startTime: "وقت البداية", endTime: "وقت النهاية", bookingSummary: "ملخص الحجز الذكي", bookingType: "نوع الحجز", discount: "الخصم", finalPrice: "السعر النهائي", remainingAfterPayments: "المتبقي بعد الدفعات", amountsAndPayments: "المبلغ والتأمين والدفعات", basePrice: "السعر الأساسي لليوم", depositAmount: "مبلغ التأمين", paymentAmount: "العربون أو مجموع الدفعات", notes: "ملاحظات اختيارية", saveBooking: "حفظ الحجز", cancel: "إلغاء", close: "إغلاق", back: "رجوع",
  morning: "صباحي", evening: "سهرة", fullDay: "24 ساعة", customPeriod: "فترة مخصصة", multiDay: "عدة أيام", waiting: "انتظار", weekend: "نهاية الأسبوع",
  confirmed: "مؤكد", awaitingDeposit: "بانتظار العربون", cancelled: "ملغي", completed: "منتهي", waitlisted: "قائمة انتظار", unpaid: "غير مدفوع", deposit: "عربون", partial: "مدفوع جزئيًا", paidInFull: "مدفوع بالكامل",
  previous: "السابق", next: "التالي", noBookingsOrWaitlist: "لا توجد حجوزات أو انتظار في هذا اليوم", allChalets: "كل الشاليهات", unselectedChalet: "الشاليه غير محدد", continuous: "مستمر",
  appearance: "المظهر", day: "نهاري", dark: "داكن", automatic: "تلقائي حسب الجهاز", deviceSettings: "إعدادات الجهاز", useDeviceLanguage: "استخدام لغة الجهاز", useDeviceAppearance: "استخدام مظهر الجهاز", haptics: "الاهتزاز", respectFontScale: "احترام حجم خط الجهاز", dateTimeSettings: "إعدادات التاريخ والوقت", timezone: "المنطقة الزمنية", deviceLanguage: "لغة الجهاز", deviceTimezone: "منطقة الجهاز الزمنية", language: "اللغة", english: "English", arabic: "العربية", saveSettings: "حفظ الإعدادات", periodSettings: "إعدادات الفترات والحجز", businessName: "اسم المنشأة", businessPhone: "رقم الهاتف", defaultCurrency: "العملة الافتراضية", weekendPrice: "سعر نهاية الأسبوع", backup: "النسخ الاحتياطي المحلي", exportBackup: "تصدير نسخة احتياطية", importBackup: "استيراد نسخة احتياطية", localBackupDescription: "يمكنك تصدير بيانات الحجوزات كملف JSON أو استيراد نسخة سابقة من الجهاز.", timeSettingsDescription: "يُستخدم التاريخ الميلادي وتُحفظ تواريخ الحجوزات دون تحويل UTC.", useDeviceLanguageDescription: "يتعرف التطبيق تلقائيًا على العربية أو الإنجليزية من إعدادات الجهاز.", useDeviceAppearanceDescription: "يتبع التطبيق الوضع النهاري أو الداكن المختار في الجهاز.", hapticsDescription: "تشغيل اهتزاز خفيف عند تنفيذ الإجراءات الأساسية.", notificationsDescription: "السماح بإعدادات التنبيهات المحلية للتطبيق.", fontScaleDescription: "الحفاظ على قابلية القراءة عند تكبير خط الجهاز.", timezoneDescription: "تُستخدم للعرض فقط ولا تغيّر تاريخ الحجز المحفوظ.", saved: "تم الحفظ", savedSettings: "تم حفظ إعدادات التطبيق محليًا.",
  filePreview: "معاينة الملف", fileReady: "الملف جاهز للمراجعة", fileDetails: "تفاصيل الملف", detectedBookings: "الحجوزات المكتشفة", detectedWaitlist: "عناصر قائمة الانتظار", replaceFile: "استبدال الملف", confirmImport: "تأكيد واستيراد الحجوزات", importWarning: "سيتم استبدال بياناتك الحالية بعد التأكيد.", importComplete: "تم الاستيراد", importCompleteDescription: "تم حفظ بيانات النسخة الاحتياطية بنجاح.", fileSize: "حجم الملف", unknownFileSize: "غير معروف", noBookingsInFile: "لا توجد حجوزات في هذا الملف.",
};

const en: TranslationMap = {
  appName: "My Booking Manager", welcome: "Welcome", home: "Home", bookings: "Bookings", calendar: "Calendar", reports: "Reports", settings: "Settings", waitlist: "Waitlist", more: "More", crm: "Customers", notifications: "Notifications", maintenance: "Maintenance",
  addBooking: "Add new booking", noBookings: "No bookings", quickActions: "Quick actions", totalBookings: "Total bookings", paid: "Paid", remaining: "Remaining", finalRevenue: "Final revenue", discounts: "Total discounts", bookingCount: "Bookings", today: "Today", upcoming: "Upcoming",
  bookingDetails: "Booking details", customerData: "Customer data", customerName: "Customer name", phone: "Phone number", chaletName: "Chalet name", period: "Gregorian period", startDate: "Start date", endDate: "End date", startTime: "Start time", endTime: "End time", bookingSummary: "Booking summary", bookingType: "Booking type", discount: "Discount", finalPrice: "Final price", remainingAfterPayments: "Remaining after payments", amountsAndPayments: "Amounts and payments", basePrice: "Base daily price", depositAmount: "Security deposit", paymentAmount: "Deposit or total payments", notes: "Optional notes", saveBooking: "Save booking", cancel: "Cancel", close: "Close", back: "Back",
  morning: "Morning", evening: "Evening", fullDay: "24 hours", customPeriod: "Custom period", multiDay: "Multiple days", waiting: "Waitlist", weekend: "Weekend",
  confirmed: "Confirmed", awaitingDeposit: "Awaiting deposit", cancelled: "Cancelled", completed: "Completed", waitlisted: "Waitlisted", unpaid: "Unpaid", deposit: "Deposit", partial: "Partially paid", paidInFull: "Paid in full",
  previous: "Previous", next: "Next", noBookingsOrWaitlist: "No bookings or waitlist entries for this day", allChalets: "All chalets", unselectedChalet: "Chalet not specified", continuous: "Continuing",
  appearance: "Appearance", day: "Light", dark: "Dark", automatic: "Automatic", deviceSettings: "Device settings", useDeviceLanguage: "Use device language", useDeviceAppearance: "Use device appearance", haptics: "Haptics", respectFontScale: "Respect device font size", dateTimeSettings: "Date and time settings", timezone: "Time zone", deviceLanguage: "Device language", deviceTimezone: "Device time zone", language: "Language", english: "English", arabic: "العربية", saveSettings: "Save settings", periodSettings: "Booking period settings", businessName: "Business name", businessPhone: "Business phone", defaultCurrency: "Default currency", weekendPrice: "Weekend price", backup: "Local backup", exportBackup: "Export backup", importBackup: "Import backup", localBackupDescription: "Export booking data as JSON or import a previous device backup.", timeSettingsDescription: "The app uses Gregorian dates and stores booking dates without UTC conversion.", useDeviceLanguageDescription: "The app detects Arabic or English from the device settings.", useDeviceAppearanceDescription: "The app follows the device light or dark appearance.", hapticsDescription: "Use light feedback for primary actions.", notificationsDescription: "Allow local notification settings for the app.", fontScaleDescription: "Keep content readable when the device font is enlarged.", timezoneDescription: "Used for display only; it never changes the saved booking date.", saved: "Saved", savedSettings: "App settings saved locally.",
  filePreview: "File preview", fileReady: "File ready to review", fileDetails: "File details", detectedBookings: "Detected bookings", detectedWaitlist: "Waitlist entries", replaceFile: "Replace file", confirmImport: "Confirm and import bookings", importWarning: "Your current data will be replaced after confirmation.", importComplete: "Import complete", importCompleteDescription: "The backup data has been saved successfully.", fileSize: "File size", unknownFileSize: "Unknown", noBookingsInFile: "This file contains no bookings.",
};

const dictionaries: Record<"ar" | "en", TranslationMap> = { ar, en };

export function useI18n() {
  const { language, direction, isRTL } = useAppPreferences();
  const t = (key: TranslationKey) => dictionaries[language][key];
  return { language, direction, isRTL, t };
}

export function getTranslation(language: "ar" | "en", key: TranslationKey) {
  return dictionaries[language][key];
}
