import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState, type ReactNode } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ChaletSwitcher } from "@/components/chalet-switcher";
import { CompactScreenHeader } from "@/components/compact-screen-header";
import { GlowGlassCard } from "@/components/glow-glass-card";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { PERIOD_COLORS, formatMoney, paymentMethodLabel, todayISO } from "@/lib/booking-model";
import { useBookings } from "@/lib/booking-store";
import { useChaletScope } from "@/lib/chalet-scope";
import { useI18n } from "@/lib/i18n";
import { buildReportBusinessInsights } from "@/lib/report-insights";
import { exportFinancialReportPdf } from "@/lib/report-export";
import { REPORT_PAYMENT_METHODS, type ReportPaymentMethod, type ReportRange, selectReportBookings, selectReportExpenses, summarizeFinancialReport } from "@/lib/reporting";
import { useWorkspaceAccess } from "@/lib/workspace-access";

type MetricTone = "neutral" | "collected" | "pending";
const TONES = { neutral: "#0F8B83", collected: "#10B981", pending: "#F59E0B", deposit: "#06B6D4" } as const;

export default function ReportsScreen() {
  const { bookings, expenses = [], settings, chalets } = useBookings();
  const { selectedChaletId } = useChaletScope();
  const { t, isRTL, language } = useI18n();
  const colors = useColors();
  const { can } = useWorkspaceAccess();
  const [range, setRange] = useState<ReportRange>("month");
  const [isExporting, setIsExporting] = useState(false);
  const today = todayISO();
  const align = isRTL ? "right" : "left";
  const row = isRTL ? "row-reverse" : "row";
  const ranges: [ReportRange, string][] = [["today", t("today")], ["month", language === "ar" ? "هذا الشهر" : "This month"], ["all", language === "ar" ? "كل الوقت" : "All time"]];
  const list = useMemo(() => selectReportBookings(bookings, range, today, selectedChaletId), [bookings, range, selectedChaletId, today]);
  const reportExpenses = useMemo(() => selectReportExpenses(expenses, range, today, selectedChaletId), [expenses, range, selectedChaletId, today]);
  const summary = useMemo(() => summarizeFinancialReport(list, chalets, reportExpenses), [chalets, list, reportExpenses]);
  const insights = useMemo(() => buildReportBusinessInsights(bookings, chalets, range, today, selectedChaletId), [bookings, chalets, range, selectedChaletId, today]);
  const selectedChalet = chalets.find((chalet) => chalet.id === selectedChaletId);
  const scopeLabel = selectedChalet?.name ?? (language === "ar" ? "جميع الشاليهات" : "All chalets");
  const periodLabel = ranges.find(([key]) => key === range)?.[1] ?? "";
  const paymentMethodLabels = useMemo(() => REPORT_PAYMENT_METHODS.reduce<Record<ReportPaymentMethod, string>>((labels, method) => { labels[method] = paymentMethodLabel(method, language); return labels; }, { "cash-guardian": "", "cash-owner": "", click: "" }), [language]);
  const periodBreakdown = [
    { key: "morning", label: language === "ar" ? "صباحي" : "Morning", color: PERIOD_COLORS.morning },
    { key: "evening", label: language === "ar" ? "سهرة" : "Evening", color: PERIOD_COLORS.evening },
    { key: "24h", label: language === "ar" ? "24 ساعة" : "24 hours", color: PERIOD_COLORS["24h"] },
    { key: "multi-day", label: language === "ar" ? "عدة أيام" : "Multi-day", color: PERIOD_COLORS["multi-day"] },
  ] as const;
  const maxPeriodCount = Math.max(1, ...periodBreakdown.map((period) => list.filter((booking) => booking.bookingType === period.key).length));
  const maxChaletRevenue = Math.max(1, ...summary.chaletPerformance.map((chalet) => chalet.revenue));
  const collectionProgress = summary.rentalTotal > 0 ? Math.min(100, (summary.paid / summary.rentalTotal) * 100) : 0;
  const delegatedSettlements = summary.collectionSettlements.filter((settlement) => settlement.recipientType !== "owner");
  const delegatedFundsHeld = delegatedSettlements.reduce((sum, settlement) => sum + settlement.fundsHeld, 0);
  const delegatedCommission = delegatedSettlements.reduce((sum, settlement) => sum + settlement.commission, 0);
  const netDueToOwner = delegatedSettlements.reduce((sum, settlement) => sum + settlement.netDueToOwner, 0);
  const delegatedHolderNames = delegatedSettlements.map((settlement) => settlement.handlerName).join("، ");
  const primaryMetrics: { title: string; value: string; icon: "event" | "account-balance-wallet" | "payments" | "pending-actions" | "receipt-long" | "trending-up"; tone: MetricTone }[] = [
    { title: t("bookingCount"), value: String(summary.bookingCount), icon: "event", tone: "neutral" },
    { title: language === "ar" ? "إيجار بعد الخصم" : "Rental after discount", value: formatMoney(summary.rentalTotal, settings.currency), icon: "account-balance-wallet", tone: "neutral" },
    { title: language === "ar" ? "محصل / مدفوع" : "Collected / paid", value: formatMoney(summary.paid, settings.currency), icon: "payments", tone: "collected" },
    { title: language === "ar" ? "متبقي الإيجار" : "Rental balance", value: formatMoney(summary.remaining, settings.currency), icon: "pending-actions", tone: "pending" },
    { title: language === "ar" ? "المصروفات" : "Expenses", value: formatMoney(summary.expenses, settings.currency), icon: "receipt-long", tone: "pending" },
    { title: language === "ar" ? "الربح الصافي" : "Net profit", value: formatMoney(summary.netProfit, settings.currency), icon: "trending-up", tone: "collected" },
    { title: language === "ar" ? (delegatedHolderNames ? `لدى ${delegatedHolderNames}` : "لدى الفريق") : (delegatedHolderNames ? `Held by ${delegatedHolderNames}` : "Held by team"), value: formatMoney(delegatedFundsHeld, settings.currency), icon: "payments", tone: "pending" },
    { title: language === "ar" ? "صافي تسوية المالك" : "Owner net settlement", value: formatMoney(netDueToOwner, settings.currency), icon: "account-balance-wallet", tone: "collected" },
    ...(delegatedCommission > 0 ? [{ title: language === "ar" ? "عمولات التحصيل" : "Collection commissions", value: formatMoney(delegatedCommission, settings.currency), icon: "receipt-long" as const, tone: "pending" as const }] : []),
  ];

  const exportReport = async () => {
    if (isExporting) return;
    setIsExporting(true);
    try { await exportFinancialReportPdf({ businessName: settings.businessName, currency: settings.currency, periodLabel, scopeLabel, language, summary, paymentMethodLabels }); }
    catch (error) {
      const code = error instanceof Error ? error.message : "";
      const message = code === "report-popup-blocked" ? (language === "ar" ? "منع المتصفح فتح نافذة التقرير. اسمح بالنوافذ المنبثقة ثم حاول التصدير مجددًا." : "The browser blocked the report window. Allow pop-ups, then try exporting again.") : code === "report-sharing-unavailable" ? (language === "ar" ? "لا تتوفر المشاركة على هذا الجهاز. افتح التقرير من جهاز يدعم المشاركة أو الطباعة." : "Sharing is unavailable on this device. Open the report on a device that supports sharing or printing.") : (language === "ar" ? "تعذر إنشاء التقرير الآن. تحقق من الاتصال ثم حاول مرة أخرى." : "The report could not be created. Check the connection and try again.");
      Alert.alert(language === "ar" ? "تعذر تصدير التقرير" : "Could not export report", message);
    } finally { setIsExporting(false); }
  };

  if (!can("view_financial_reports")) return <ScreenContainer><GlowGlassCard style={styles.locked} contentStyle={styles.lockedContent}><MaterialIcons name="lock" size={32} color={colors.primary} /><Text style={[styles.lockedTitle, { color: colors.foreground, textAlign: align }]}>{language === "ar" ? "هذه الصفحة غير مفعّلة لصلاحياتك" : "This page is not enabled for your permissions"}</Text><Text style={[styles.lockedText, { color: colors.muted, textAlign: align }]}>{language === "ar" ? "اطلب من المدير تفعيل صلاحية عرض التقارير المالية." : "Ask your manager to enable financial reports access."}</Text></GlowGlassCard></ScreenContainer>;

  return <ScreenContainer><ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <CompactScreenHeader title={t("reports")} logoUrl={settings.businessLogoUrl} icon="bar-chart" action={{ label: isExporting ? (language === "ar" ? "جارٍ…" : "Working…") : (language === "ar" ? "تصدير" : "Export"), accessibilityLabel: language === "ar" ? "تصدير التقرير المالي" : "Export financial report", onPress: () => void exportReport(), icon: "ios-share" }} />
    <View style={styles.scopeWrap}><ChaletSwitcher /></View>
    <GlassSection style={styles.controls} contentStyle={styles.controlsContent}><Pressable accessibilityRole="button" accessibilityLabel={language === "ar" ? "إدارة المصروفات" : "Manage expenses"} onPress={() => router.push("/expenses" as never)} style={({ pressed }) => [styles.expenseLink, { flexDirection: row, opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name="receipt-long" size={17} color={TONES.pending} /><Text style={[styles.flex, { color: TONES.pending, fontSize: 12, fontWeight: "900", textAlign: align }]}>{language === "ar" ? "إدارة المصروفات والربح الصافي" : "Manage expenses and net profit"}</Text><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={18} color={TONES.pending} /></Pressable><View style={[styles.rangeRow, { flexDirection: row }]}>{ranges.map(([key, label]) => <Pressable key={key} onPress={() => setRange(key)} style={({ pressed }) => [styles.rangeChip, { backgroundColor: range === key ? colors.primary : "transparent", opacity: pressed ? 0.75 : 1 }]}><Text numberOfLines={1} style={{ color: range === key ? "#FFFFFF" : colors.foreground, fontSize: 12, fontWeight: "800" }}>{label}</Text></Pressable>)}</View></GlassSection>
    <GlowGlassCard glowColor={colors.primary} glowTone="subtle" style={styles.summary} contentStyle={styles.summaryContent}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "800", textAlign: align }}>{language === "ar" ? "صافي التحصيل" : "Collection progress"}</Text><Text style={{ color: colors.foreground, fontSize: 30, fontWeight: "900", marginTop: 5, textAlign: align }}>{Math.round(collectionProgress)}%</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 2, textAlign: align }}>{formatMoney(summary.paid, settings.currency)} / {formatMoney(summary.rentalTotal, settings.currency)}</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { backgroundColor: colors.primary, width: `${collectionProgress}%` }]} /></View></GlowGlassCard>
    <GlassSection title={language === "ar" ? "مؤشرات القرار" : "Decision insights"} align={align}><View style={[styles.insightRow, { flexDirection: row }]}><Insight value={`${insights.occupancyRate}%`} label={language === "ar" ? "إشغال يومي" : "Day occupancy"} color="#3B82F6" /><Insight value={formatMoney(insights.expectedCollection, settings.currency)} label={language === "ar" ? `${insights.outstandingBookingCount} دفعات متوقعة` : `${insights.outstandingBookingCount} due bookings`} color="#F59E0B" /><Insight value={formatMoney(insights.overdueDepositAmount, settings.currency)} label={language === "ar" ? `${insights.overdueDepositCount} تأمين متأخر` : `${insights.overdueDepositCount} overdue deposits`} color="#06B6D4" /></View></GlassSection>
    <GlassSection title={language === "ar" ? "توزيع الفترات" : "Period distribution"} align={align}>{periodBreakdown.map((period) => { const count = list.filter((booking) => booking.bookingType === period.key).length; return <View key={period.key} style={[styles.periodRow, { flexDirection: row }]}><Text style={[styles.periodLabel, { color: colors.muted, textAlign: align }]}>{period.label}</Text><View style={styles.periodTrack}><View style={[styles.periodFill, { backgroundColor: period.color, width: `${(count / maxPeriodCount) * 100}%` }]} /></View><Text style={{ color: period.color, fontWeight: "900", fontSize: 12 }}>{count}</Text></View>; })}</GlassSection>
    <View style={styles.metrics}>{primaryMetrics.map((metric) => <MetricCard key={metric.title} metric={metric} colors={colors} align={align} />)}</View>
    <GlassSection style={styles.deposit} title={language === "ar" ? "حالة التأمين" : "Security deposits"} icon="shield" iconColor={TONES.deposit} align={align}><View style={[styles.depositValues, { flexDirection: row }]}><DepositValue label={language === "ar" ? "مسجل" : "Recorded"} value={formatMoney(summary.depositRecorded, settings.currency)} icon="security" colors={colors} /><DepositValue label={language === "ar" ? "مسترد" : "Refunded"} value={formatMoney(summary.depositRefunded, settings.currency)} icon="assignment-return" colors={colors} /><DepositValue label={language === "ar" ? "قيد الحيازة" : "Held"} value={formatMoney(summary.depositHeld, settings.currency)} icon="lock-clock" colors={colors} /></View></GlassSection>
    <GlassSection style={styles.section} title={language === "ar" ? "طرق الدفع" : "Payment methods"} subtitle={language === "ar" ? "ملخص التحصيل للفترة المحددة" : "Collection summary for this period"} icon="account-balance" iconColor={TONES.collected} align={align}>{REPORT_PAYMENT_METHODS.map((method) => <View key={method} style={[styles.paymentRow, { flexDirection: row }]}><View style={[styles.paymentMethodIcon, { backgroundColor: TONES.collected + "13" }]}><MaterialIcons name={method === "cash-guardian" ? "person" : method === "cash-owner" ? "payments" : "swap-horiz"} size={16} color={TONES.collected} /></View><Text style={[styles.flex, { color: colors.foreground, fontSize: 12, fontWeight: "700", textAlign: align }]}>{paymentMethodLabels[method]}</Text><Text style={{ color: TONES.collected, fontSize: 13, fontWeight: "900", writingDirection: "ltr" }}>{formatMoney(summary.paymentMethods[method], settings.currency)}</Text></View>)}</GlassSection>
    {!selectedChaletId ? <GlassSection style={styles.section} title={language === "ar" ? "أداء الشاليهات" : "Chalet performance"} subtitle={language === "ar" ? "الإيراد وعدد الحجوزات ضمن الفترة" : "Revenue and booking count in this period"} icon="holiday-village" iconColor={colors.primary} align={align}>{summary.chaletPerformance.length ? summary.chaletPerformance.map((chalet) => <View key={chalet.chaletId} style={styles.chaletRow}><View style={[styles.chaletMeta, { flexDirection: row }]}><View style={[styles.chaletDot, { backgroundColor: chalet.color }]} /><Text numberOfLines={1} style={[styles.flex, { color: colors.foreground, fontSize: 13, fontWeight: "900", textAlign: align }]}>{chalet.chaletName}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>{language === "ar" ? `${chalet.bookingCount} حجوزات` : `${chalet.bookingCount} bookings`}</Text></View><View style={styles.chaletTrack}><View style={[styles.chaletFill, { width: `${(chalet.revenue / maxChaletRevenue) * 100}%`, backgroundColor: chalet.color }]} /></View><Text style={{ color: chalet.color, fontSize: 12, fontWeight: "900", textAlign: align }}>{formatMoney(chalet.revenue, settings.currency)}</Text></View>) : <Text style={{ color: colors.muted, fontSize: 12, textAlign: align }}>{language === "ar" ? "لا توجد حجوزات ضمن هذه الفترة." : "No bookings in this period."}</Text>}</GlassSection> : null}
  </ScrollView></ScreenContainer>;
}

function GlassSection({ children, title, subtitle, icon, iconColor, align, style, contentStyle }: { children: ReactNode; title?: string; subtitle?: string; icon?: React.ComponentProps<typeof MaterialIcons>["name"]; iconColor?: string; align?: "left" | "right"; style?: object; contentStyle?: object }) { const colors = useColors(); const accent = iconColor ?? colors.primary; return <GlowGlassCard style={[styles.glassSection, style]} contentStyle={[styles.glassContent, contentStyle]}>{title ? <View style={[styles.sectionHead, { flexDirection: align === "right" ? "row-reverse" : "row" }]}>{icon ? <View style={[styles.sectionIcon, { backgroundColor: `${accent}18` }]}><MaterialIcons name={icon} size={18} color={accent} /></View> : null}<View style={styles.flex}><Text style={{ color: colors.foreground, fontSize: 15, fontWeight: "900", textAlign: align }}>{title}</Text>{subtitle ? <Text style={{ color: colors.muted, fontSize: 11, marginTop: 2, textAlign: align }}>{subtitle}</Text> : null}</View></View> : null}{children}</GlowGlassCard>; }

function MetricCard({ metric, colors, align }: { metric: { title: string; value: string; icon: "event" | "account-balance-wallet" | "payments" | "pending-actions" | "receipt-long" | "trending-up"; tone: MetricTone }; colors: ReturnType<typeof useColors>; align: "left" | "right" }) { const tone = TONES[metric.tone]; return <View collapsable={false} style={styles.metricCell}><GlowGlassCard style={styles.metricCard} glowColor={tone} glowTone="subtle" contentStyle={styles.metricContent}><View style={[styles.metricIcon, { backgroundColor: tone + "1A" }]}><MaterialIcons name={metric.icon} size={20} color={tone} /></View><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.68} style={{ color: colors.foreground, fontSize: 17, fontWeight: "900", marginTop: 13, textAlign: align }}>{metric.value}</Text><Text numberOfLines={1} style={{ color: colors.muted, fontSize: 11, marginTop: 4, textAlign: align }}>{metric.title}</Text></GlowGlassCard></View>; }
function DepositValue({ label, value, icon, colors }: { label: string; value: string; icon: "security" | "assignment-return" | "lock-clock"; colors: ReturnType<typeof useColors> }) { return <View style={styles.depositValue}><View style={[styles.depositIcon, { backgroundColor: TONES.deposit + "16" }]}><MaterialIcons name={icon} size={15} color={TONES.deposit} /></View><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.62} style={{ color: colors.foreground, fontSize: 12, fontWeight: "900", marginTop: 7, writingDirection: "ltr", textAlign: "center" }}>{value}</Text><Text numberOfLines={1} style={{ color: colors.muted, fontSize: 10, marginTop: 3, textAlign: "center" }}>{label}</Text></View>; }
function Insight({ value, label, color }: { value: string; label: string; color: string }) { return <View style={styles.insight}><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.65} style={{ color, fontSize: 13, fontWeight: "900", writingDirection: "ltr", textAlign: "center" }}>{value}</Text><Text numberOfLines={2} style={{ color: "#94A3B8", fontSize: 9, marginTop: 4, textAlign: "center" }}>{label}</Text></View>; }

const styles = StyleSheet.create({
  scroll: { flex: 1, minHeight: 0 }, content: { padding: 16, paddingBottom: 36 }, flex: { flex: 1, minWidth: 0 }, scopeWrap: { marginTop: 11 }, controls: { marginTop: 10, borderRadius: 20 }, controlsContent: { padding: 8 }, expenseLink: { minHeight: 44, borderRadius: 14, paddingHorizontal: 11, alignItems: "center", gap: 7 }, rangeRow: { gap: 8, marginTop: 8 }, rangeChip: { flex: 1, minWidth: 0, minHeight: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", paddingHorizontal: 4 }, summary: { borderRadius: 24, marginTop: 14 }, summaryContent: { padding: 18 }, progressTrack: { height: 7, borderRadius: 4, marginTop: 14, overflow: "hidden", backgroundColor: "rgba(255,255,255,0.12)" }, progressFill: { height: "100%", borderRadius: 4 }, glassSection: { borderRadius: 22, marginTop: 14 }, glassContent: { padding: 14 }, sectionHead: { alignItems: "center", gap: 9 }, sectionIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" }, insightRow: { gap: 7, marginTop: 12 }, insight: { flex: 1, minWidth: 0, alignItems: "center" }, periodRow: { alignItems: "center", gap: 8, marginTop: 10 }, periodLabel: { width: 72, fontSize: 11, fontWeight: "700" }, periodTrack: { flex: 1, height: 8, borderRadius: 5, overflow: "hidden", backgroundColor: "rgba(7,11,18,0.18)" }, periodFill: { height: "100%", borderRadius: 5 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginTop: 14 }, metricCell: { flexBasis: "48%", maxWidth: "48%", minWidth: 0, minHeight: 118 }, metricCard: { flex: 1, minHeight: 118, borderRadius: 22 }, metricContent: { minHeight: 118, padding: 14 }, metricIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, deposit: { marginTop: 10 }, depositValues: { gap: 6, marginTop: 12 }, depositValue: { flex: 1, minWidth: 0, alignItems: "center", paddingHorizontal: 3 }, depositIcon: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center" }, section: { marginTop: 14 }, paymentRow: { minHeight: 45, alignItems: "center", gap: 9, marginTop: 9, paddingTop: 9 }, paymentMethodIcon: { width: 28, height: 28, borderRadius: 9, alignItems: "center", justifyContent: "center" }, chaletRow: { marginTop: 13 }, chaletMeta: { alignItems: "center", gap: 7 }, chaletDot: { width: 9, height: 9, borderRadius: 5 }, chaletTrack: { height: 7, borderRadius: 5, overflow: "hidden", marginTop: 7, backgroundColor: "rgba(7,11,18,0.18)" }, chaletFill: { height: "100%", borderRadius: 5 }, locked: { borderRadius: 24, padding: 20, margin: 16, marginTop: 32 }, lockedContent: { alignItems: "center" }, lockedTitle: { fontSize: 18, fontWeight: "900", marginTop: 12, width: "100%" }, lockedText: { fontSize: 13, lineHeight: 20, marginTop: 7, width: "100%" },
});
